version = 1

test_patterns = [
  'podaac/tests/**'
]

exclude_patterns = [
  'docs/**',
  'examples/**'
]

[[ analyzers ]]
name = 'python'
enabled = true
  [analyzers.meta]
  max_line_length = 100
  skip_doc_coverage = ["module", "magic", "class"]
